//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGBKeyboardSpectrograph.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingKeyboardModel {
            get {
                return ((string)(this["settingKeyboardModel"]));
            }
            set {
                this["settingKeyboardModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingKeyboardLayout {
            get {
                return ((string)(this["settingKeyboardLayout"]));
            }
            set {
                this["settingKeyboardLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int spectroAmplitude {
            get {
                return ((int)(this["spectroAmplitude"]));
            }
            set {
                this["spectroAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int spectroBackgroundBrightness {
            get {
                return ((int)(this["spectroBackgroundBrightness"]));
            }
            set {
                this["spectroBackgroundBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int debugLogLevel {
            get {
                return ((int)(this["debugLogLevel"]));
            }
            set {
                this["debugLogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool settingMinimizeToTray {
            get {
                return ((bool)(this["settingMinimizeToTray"]));
            }
            set {
                this["settingMinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int spectroRefreshDelay {
            get {
                return ((int)(this["spectroRefreshDelay"]));
            }
            set {
                this["spectroRefreshDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color spectroColorBars {
            get {
                return ((global::System.Drawing.Color)(this["spectroColorBars"]));
            }
            set {
                this["spectroColorBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color spectroColorBackground {
            get {
                return ((global::System.Drawing.Color)(this["spectroColorBackground"]));
            }
            set {
                this["spectroColorBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rainbow")]
        public string spectroColorBackgroundType {
            get {
                return ((string)(this["spectroColorBackgroundType"]));
            }
            set {
                this["spectroColorBackgroundType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingUsb3Mode {
            get {
                return ((bool)(this["settingUsb3Mode"]));
            }
            set {
                this["settingUsb3Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingShowGraphics {
            get {
                return ((bool)(this["settingShowGraphics"]));
            }
            set {
                this["settingShowGraphics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104")]
        public float spectroBackgroundEffectWidth {
            get {
                return ((float)(this["spectroBackgroundEffectWidth"]));
            }
            set {
                this["spectroBackgroundEffectWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float spectroBackgroundEffectSpeed {
            get {
                return ((float)(this["spectroBackgroundEffectSpeed"]));
            }
            set {
                this["spectroBackgroundEffectSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingStartMinimized {
            get {
                return ((bool)(this["settingStartMinimized"]));
            }
            set {
                this["settingStartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingEffectsOnStart {
            get {
                return ((bool)(this["settingEffectsOnStart"]));
            }
            set {
                this["settingEffectsOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104")]
        public float spectroBarEffectWidth {
            get {
                return ((float)(this["spectroBarEffectWidth"]));
            }
            set {
                this["spectroBarEffectWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float spectroBarEffectSpeed {
            get {
                return ((float)(this["spectroBarEffectSpeed"]));
            }
            set {
                this["spectroBarEffectSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int spectroCaptureMode {
            get {
                return ((int)(this["spectroCaptureMode"]));
            }
            set {
                this["spectroCaptureMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string spectroCaptureDevice {
            get {
                return ((string)(this["spectroCaptureDevice"]));
            }
            set {
                this["spectroCaptureDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string spectroColorBarsType {
            get {
                return ((string)(this["spectroColorBarsType"]));
            }
            set {
                this["spectroColorBarsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int spectroBarBrightness {
            get {
                return ((int)(this["spectroBarBrightness"]));
            }
            set {
                this["spectroBarBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingRestoreLighting {
            get {
                return ((bool)(this["settingRestoreLighting"]));
            }
            set {
                this["settingRestoreLighting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingCueLocation {
            get {
                return ((string)(this["settingCueLocation"]));
            }
            set {
                this["settingCueLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingLaunchCueOnExit {
            get {
                return ((bool)(this["settingLaunchCueOnExit"]));
            }
            set {
                this["settingLaunchCueOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingSpectroOnStart {
            get {
                return ((bool)(this["settingSpectroOnStart"]));
            }
            set {
                this["settingSpectroOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingStaticOnStart {
            get {
                return ((bool)(this["settingStaticOnStart"]));
            }
            set {
                this["settingStaticOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appLastUsedProfile {
            get {
                return ((string)(this["appLastUsedProfile"]));
            }
            set {
                this["appLastUsedProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Eff_RL_S_Mode {
            get {
                return ((int)(this["Eff_RL_S_Mode"]));
            }
            set {
                this["Eff_RL_S_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Eff_RL_S_DefinedColor {
            get {
                return ((global::System.Drawing.Color)(this["Eff_RL_S_DefinedColor"]));
            }
            set {
                this["Eff_RL_S_DefinedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Eff_RL_S_CLow_Red {
            get {
                return ((int)(this["Eff_RL_S_CLow_Red"]));
            }
            set {
                this["Eff_RL_S_CLow_Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Eff_RL_S_CLow_Green {
            get {
                return ((int)(this["Eff_RL_S_CLow_Green"]));
            }
            set {
                this["Eff_RL_S_CLow_Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Eff_RL_S_CLow_Blue {
            get {
                return ((int)(this["Eff_RL_S_CLow_Blue"]));
            }
            set {
                this["Eff_RL_S_CLow_Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Eff_RL_S_CHigh_Red {
            get {
                return ((int)(this["Eff_RL_S_CHigh_Red"]));
            }
            set {
                this["Eff_RL_S_CHigh_Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Eff_RL_S_CHigh_Green {
            get {
                return ((int)(this["Eff_RL_S_CHigh_Green"]));
            }
            set {
                this["Eff_RL_S_CHigh_Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Eff_RL_S_CHigh_Blue {
            get {
                return ((int)(this["Eff_RL_S_CHigh_Blue"]));
            }
            set {
                this["Eff_RL_S_CHigh_Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Eff_RL_E_Mode {
            get {
                return ((int)(this["Eff_RL_E_Mode"]));
            }
            set {
                this["Eff_RL_E_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Eff_RL_E_DefinedColor {
            get {
                return ((global::System.Drawing.Color)(this["Eff_RL_E_DefinedColor"]));
            }
            set {
                this["Eff_RL_E_DefinedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Eff_RL_E_CLow_Red {
            get {
                return ((int)(this["Eff_RL_E_CLow_Red"]));
            }
            set {
                this["Eff_RL_E_CLow_Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Eff_RL_E_CLow_Green {
            get {
                return ((int)(this["Eff_RL_E_CLow_Green"]));
            }
            set {
                this["Eff_RL_E_CLow_Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Eff_RL_E_CLow_Blue {
            get {
                return ((int)(this["Eff_RL_E_CLow_Blue"]));
            }
            set {
                this["Eff_RL_E_CLow_Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Eff_RL_E_CHigh_Red {
            get {
                return ((int)(this["Eff_RL_E_CHigh_Red"]));
            }
            set {
                this["Eff_RL_E_CHigh_Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Eff_RL_E_CHigh_Green {
            get {
                return ((int)(this["Eff_RL_E_CHigh_Green"]));
            }
            set {
                this["Eff_RL_E_CHigh_Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Eff_RL_E_CHigh_Blue {
            get {
                return ((int)(this["Eff_RL_E_CHigh_Blue"]));
            }
            set {
                this["Eff_RL_E_CHigh_Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Eff_RL_Duration {
            get {
                return ((int)(this["Eff_RL_Duration"]));
            }
            set {
                this["Eff_RL_Duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Eff_RL_Delay {
            get {
                return ((int)(this["Eff_RL_Delay"]));
            }
            set {
                this["Eff_RL_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EffectUseStaticKeys {
            get {
                return ((bool)(this["EffectUseStaticKeys"]));
            }
            set {
                this["EffectUseStaticKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int idleTriggerTime {
            get {
                return ((int)(this["idleTriggerTime"]));
            }
            set {
                this["idleTriggerTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Random Lights")]
        public string idleMode {
            get {
                return ((string)(this["idleMode"]));
            }
            set {
                this["idleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string idleProfile {
            get {
                return ((string)(this["idleProfile"]));
            }
            set {
                this["idleProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool idleUseIdleWatcher {
            get {
                return ((bool)(this["idleUseIdleWatcher"]));
            }
            set {
                this["idleUseIdleWatcher"] = value;
            }
        }
    }
}
